version: "3.9"

services:
  mhfrontier-cq-tool-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mhfrontier-cq-tool-api
    ports:
      - "5001:5001"
    env_file:
      - .env